---
plugin: theforeman.foreman.foreman

url: "https://192.168.241.149"
user: "admin"
password: "password"

validate_certs: false
use_reports_api: false

compose:
  ansible_host: ip

want_hostcollections: true
group_prefix: "foreman_"
