all:
  children:

    linux:
      children:

        lmint:
          hosts:
            lmint-virtual-machine:
              ansible_host: 192.168.241.145
        
        rhel_servers:
          hosts:
            newgl-rhelvm01:
              ansible_host: 192.168.241.146

            newgl-rhelvm02:
              ansible_host: 192.168.241.147

        alma_servers:
          hosts:
            almalinuxvm01:
              ansible_host: 192.168.241.154

      vars:
        ansible_user: masterubuntu
        ansible_ssh_private_key_file: ~/.ssh/id_ed25519
        ansible_python_interpreter: /usr/bin/python3
          #ansible_become: True

    windows_server:
      hosts:
        test-svm-01.gelord.org:
          ansible_host: 192.168.241.142
          ansible_port: 5985

      vars:
        ansible_user: administrator
        ansible_password: "Password@#12345"
          #ansible_become: False
        ansible_connection: winrm
        ansible_winrm_transport: ntlm
