---
- name: Collect OS Information
  hosts: all
  gather_facts: yes

  tasks:

    - debug:
        msg:
          - "Hostname: {{ hostnam e}}"
          - "OS: {{ ansible_distribution }}"
          - "Version: {ansible_distribution_version }}"
          - "Memory MB: {{ ansible_memtotal_mb }}"
          - "CPU: {{ ansible_processor_vcpus }}"
